--- 
version: "3.2"
services: 
  firefly_iii_app: 
    image: jc5x/firefly-iii:latest
    env_file: .firefly.env
    depends_on:
      - firefly_iii_db
    networks: 
      - firefly_iii_net
    ports: 
      - "80:80"
    volumes: 
      - 
        source: firefly_iii_export
        target: /var/www/firefly-iii/storage/export
        type: volume
      - 
        source: firefly_iii_upload
        target: /var/www/firefly-iii/storage/upload
        type: volume

  firefly_iii_db: 
    image: "postgres:10"
    env_file: .psql.env
    networks: 
      - firefly_iii_net
    volumes: 
      - firefly_iii_db:/var/lib/postgresql/data

volumes: 
  firefly_iii_db: ~
  firefly_iii_export: ~
  firefly_iii_upload: ~

networks: 
  firefly_iii_net: 
    driver: bridge
